# Generated by Django 4.2.4 on 2023-09-08 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0001_initial'),
        ('songs', '0002_alter_songs_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='submoods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moods.submoods'),
        ),
    ]
