# Generated by Django 4.2.4 on 2023-09-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('spotify_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('song', models.ManyToManyField(related_name='playlists', to='songs.songs')),
            ],
        ),
    ]
