# Generated by Django 4.2.4 on 2023-09-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
