# Generated by Django 4.2.4 on 2023-09-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_alter_songs_submoods'),
        ('playlists', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='song',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='songs.songs'),
        ),
    ]
