# Generated by Django 4.2.4 on 2023-09-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='spotify_display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
